### ISSUE TITLE
(BUG) Install script fails to download tar, keeps going

### ISSUE THREAD

**Issue by op-ct** [puppetlabs/pdkgo#125]
**Describe the bug**

I tried installing pdkgo earlier today with the `install.sh` script, and it failed with `gzip: stdin: not in gzip format` because it was trying to download the wrong URL for the tarball.

* After poking about, I noticed this was because the variable `$ver` had ended up with two matches: `0.1.0 0.1.0-pre`.
* The script kept going even though there was a failure, reminding me to add pct to my path (although it wasn't  there).

**To Reproduce**

1. Run the `curl -L https://pup.pt/pdkgo/install.sh | sh` command

**Expected behavior**

* The downloader should select a single tarfile and download it correctly.
* If something fails, the script should not proceed any further.

**Screenshots or logs**

```console
[user@host ~]$ curl -L https://pup.pt/pdkgo/install.sh | sh
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   776  100   776    0     0   1442      0 --:--:-- --:--:-- --:--:--  1442
Downloading and extracting pct 0.1.0
0.1.0-pre to /home/user/.puppetlabs/pct
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Remember to add the pct app to your path:
export PATH=$PATH:/home/user/.puppetlabs/pct
[user@host ~]$ 
```

**What versions are you running?:**
 - OS: Windows 10 / WSL 2.0 / Fedora 31
 - PCT Version 0.1.0 (+0.1.0-pre, together)

**Comment by binford2k** [comment]
yay for consistency right? Here's the BSD `grep -m flag`

```
     -m num, --max-count=num
             Stop reading the file after num matches.
```

And here's the GNU version.

```
       -m NUM, --max-count=NUM
              Stop  reading  a file after NUM matching lines.  If the input is standard input from a regular file, and NUM matching lines are output, grep ensures that the standard input is positioned to just after the last matching line before exiting, regardless of the presence of
              trailing context lines.  This enables a calling process to resume a search.  When grep stops after NUM matching lines, it outputs any trailing context lines.  When the -c or --count option is also used, grep does not output a count greater than NUM.   When  the  -v  or
              --invert-match option is also used, grep stops after outputting NUM non-matching lines.
```

The releases JSON is all one line.....
