### ISSUE TITLE
SPIKE: Investigate telemetry solution

### ISSUE THREAD

**Issue by jpogran** [puppetlabs/pdkgo#130]
Determine whether we hook in to existing PDK stats

**Comment by sanfrancrisko** [comment]
We should take a look at how the [WaSH](https://github.com/puppetlabs/wash) project is using Go's telemetry tools

**Comment by sanfrancrisko** [comment]
- Determine if we can implement telemetry at all
- Can we send this to Google Analytics?
- Determine how similar / different this will potentially be to existing metrics collected for PDK

**Comment by da-ar** [comment]
https://docs.google.com/document/d/1TS9kWq9X5lEi8-Byec-o_bCu-9Assi-VBV2_1UX5PAM/edit?usp=sharing
