### ISSUE TITLE
Implement telemetry in the pdkgo command line

### ISSUE THREAD

**Issue by jpogran** [puppetlabs/pdkgo#131]
- [ ] Analytics API from Wash integrated into PCT
- [ ] Compile flags added for identifying Analytics code
- [ ] GoReleaser Updated to produce 2 separate binaries, one with and one without Analytics code
- [ ] Creation of 2 Google Analytics ids one for production and one for testing/development
  - these should not be the same as the existing PDK
- [ ] Capture CLI called and OS/ARCH

**Comment by sanfrancrisko** [comment]
This will be based off the outcome in #130
