### ISSUE TITLE
Verify that the ruby tar and gzip methods can extract a PCT tar/gzip'd file

### ISSUE THREAD

**Issue by jpogran** [puppetlabs/pdkgo#155]

**Comment by sanfrancrisko** [comment]
Verified by creating a `.tar.gz` of a module using the GZip and Tar utility methods added as part of #137, then wrote a Ruby script to extract them in a similar manner as performed in [forge-web-api](https://github.com/puppetlabs/puppet-forge-api/blob/9a5bf821a2c04d718c139134539814c3a553e9da/lib/api/tarball_reader.rb#L70-L76)
