### ISSUE TITLE
Determine storage place for starter Puppet Content Templates

### ISSUE THREAD

**Issue by jpogran** [puppetlabs/pdkgo#20]
Evaluate storing templates in one github repo or multiple, take into consideration adding this to the automatic pdkgo release process

This ticket purely handles where we are storing in VCS the initial set of example templates. Decide if we store in one repo per template or one repo as a starter pack. This will create tickets on either architectural detail and/or repo creation.

- If we store as one repo per template, we need to figure out repo naming, template naming and local folder naming.
- If we store as a temporary 'starter' repo, we can archive as we discover final implementation.

**Comment by sanfrancrisko** [comment]
For the purposes of the LA release, the content templates are going to reside in one temporary repo that will be destroyed when the first GA release is available: https://github.com/puppetlabs/baker-round/

There are a few methods we could use to package the templates:

## Option 1: Bundle templates with binary
- Build process pulls from https://github.com/puppetlabs/baker-round/ -> `$PROJECT_ROOT/pct/templates`
- Templates packaged up with binary; new one would need to be created each time we add / modify templates
- `pct.go` would need modified to look in `$PROJECT_ROOT/pct/templates` for templates

## Option 2: Add "fetch-templates" command
- Have a command (TBD) that pulls from https://github.com/puppetlabs/baker-round/ -> `~/.pdk/pct`
- We would potentially need to start considering splitting in to "builtin" vs "custom", in case people want to experiment with adding their own templates and a "fetch-templates" doesn't overwrite anything:
```
tree pct
pct
├── builtin
└── custom
```

**Comment by sanfrancrisko** [comment]
To capture some disparate conversations about the actual GA implementation:
- There seems to be consensus amongst the team to go for a 1-1 template-repo structure
- We can facilitate collections of templates by having a repo act as a pointer to the individual repos that make up the collections. We can start having nice things like:
  - Version / tag pinning

**Comment by sanfrancrisko** [comment]
We have decided to go for **Option 1** above.

**Comment by sanfrancrisko** [comment]
- [ ] Update docs to reflect the builtin templates functionality
- [ ] Update build scripts to fetch templates from `baker-round` prior to executing `goreleaser`
