### ISSUE TITLE
Update README.md GIFS in puppetlabs/pdkgo

### ISSUE THREAD

**Issue by sanfrancrisko** [puppetlabs/pdkgo#252]
There are sections of the `README.md` that are out of date, due to the product output changing and new functionality being added.

It would also be good to regenerate the GIFs with [terminalizer](https://github.com/faressoft/terminalizer), to make them more legible.

Another issue is that the GIFs live in the repo and are quite large - they should be split out to somewhere separate, if possible.

**Acceptance Criteria:**

- [x] Regenerate GIFs with [terminalizer](https://github.com/faressoft/terminalizer)
- [x] Move GIFs to a separate location, if possible
- [x] Update [`Quick Start Guide -> Step 1` GIF](https://github.com/puppetlabs/pdkgo#step-1-create-a-puppet-module) to use new `namespace/template_id` template structure
- [x] Update [`Quick Start Guide -> Step 2` GIF](https://github.com/puppetlabs/pdkgo#step-2-add-a-new-class) to use new `namespace/template_id` template structure
- [x] Update [`Quick Start Guide -> Step 3` GIFs](https://github.com/puppetlabs/pdkgo#step-3-add-a-github-actions-workflow) to use new `namespace/template_id` template structure

**Comment by michaeltlombardi** [comment]
Closed by #253
