### ISSUE TITLE
SPIKE: PCT name and Folder name conventions and requirements

### ISSUE THREAD

**Issue by jpogran** [puppetlabs/pdkgo#26]

**Comment by jpogran** [comment]
Currently the folder name and the PCT ID (name) have to be the same in order for PDK to find it. This is because the implementation walks a directory looking for properly named config files. 

Does this mean the github repo a PCT is stored in has to be the same as the ID of the PCT?
Should `pdk build <pct_template>` handle correctly naming the folder for deployment like `pdk build <module>` does? This would mean the user doesn't have to know to name things 'correctly' before use
If folder names have to be the same as PCT IDs, then that means they have to be unique on the forge even though there's namespaces. Should the folder name be `user-nameof-thing` when deployed to avoid name clashes?

**Comment by sanfrancrisko** [comment]
We have come to the consensus of:

`namespace/template_name` as unique ID. We should have the TAB'ing user experience allow the user to tab over the `template_name` but then we will offer all template names across multiple namespaces.

Folder structure:

`$TEMPLATE_DIR/namespace/template_name/pct-config.yml`

**NOTE:** We will not be versioning on disk, we'll be overwriting with the latest when updating.

See [this section of the doc](https://docs.google.com/document/d/1DUqP_4nvsHFHqEKAL63gQNmt1PGYBBaJdsoQkezpnkk/edit#heading=h.oh4opxx47wlg) for more details.

**Comment by sanfrancrisko** [comment]
Other considerations:

- Template name conventions (e.g. underscores vs dashes, special chars)
