### ISSUE TITLE
IAC Blog Post announcing PCT LA release

### ISSUE THREAD

**Issue by sanfrancrisko** [puppetlabs/pdkgo#45]
We should write a blog post for the [IAC Blog](https://puppetlabs.github.io/iac/) announcing the availability of the PCT LA release.

What would also be nice to include is:
- Details on how to provide feedback (via a Github Discussion or something similar)
- Where to raise questions (Slack, Github, etc...)

**Comment by sanfrancrisko** [comment]
Created PR for review here: https://github.com/puppetlabs/iac/pull/263

**Comment by jpogran** [comment]
Draft up here https://github.com/puppetlabs/iac/pull/265
